from typing import Dict, Any, List
from fpdf import FPDF

def generate_interview_pdf(
    candidate_name: str,
    job_role: str,
    report: Dict[str, Any],
    transcript: List[Dict[str, str]],
) -> bytes:
    """
    Generates a high-fidelity PDF interview report.
    """
    class PDF(FPDF):
        def header(self):
            self.set_font("helvetica", "B", 15)
            self.set_text_color(124, 58, 237) # Vedrix Purple
            self.cell(0, 10, "Vedrix AI - Candidate Evaluation Report", border=False, align="C", new_x="LMARGIN", new_y="NEXT")
            self.set_draw_color(124, 58, 237)
            self.line(10, 20, 200, 20)
            self.ln(10)

        def footer(self):
            self.set_y(-15)
            self.set_font("helvetica", "I", 8)
            self.set_text_color(128, 128, 128)
            self.cell(0, 10, f"Page {self.page_no()}/{{nb}} - Generated by Vedrix AI Platform", align="C")

    pdf = PDF()
    pdf.add_page()
    
    # Hero Info
    pdf.set_font("helvetica", "B", 12)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(40, 8, "Candidate:")
    pdf.set_font("helvetica", "", 12)
    pdf.cell(0, 8, candidate_name, new_x="LMARGIN", new_y="NEXT")

    pdf.set_font("helvetica", "B", 12)
    pdf.cell(40, 8, "Role:")
    pdf.set_font("helvetica", "", 12)
    pdf.cell(0, 8, job_role, new_x="LMARGIN", new_y="NEXT")

    pdf.set_font("helvetica", "B", 12)
    pdf.cell(40, 8, "Score:")
    pdf.set_font("helvetica", "B", 14)
    pdf.set_text_color(52, 211, 153) # Greenish
    pdf.cell(0, 8, f"{report.get('overall_score', 'N/A')} / 10.0", new_x="LMARGIN", new_y="NEXT")
    
    pdf.set_font("helvetica", "B", 12)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(40, 8, "Decision:")
    pdf.set_font("helvetica", "B", 12)
    pdf.cell(0, 8, str(report.get('hire_recommendation', 'N/A')).upper(), new_x="LMARGIN", new_y="NEXT")
    pdf.ln(10)

    # Score Breakdown
    pdf.set_font("helvetica", "B", 14)
    pdf.set_text_color(124, 58, 237)
    pdf.cell(0, 10, "Score Breakdown", border="B", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(3)
    pdf.set_font("helvetica", "B", 11)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(60, 8, "Technical Accuracy:")
    pdf.set_font("helvetica", "", 11)
    pdf.cell(0, 8, str(report.get('technical_accuracy', 'N/A')), new_x="LMARGIN", new_y="NEXT")
    
    pdf.set_font("helvetica", "B", 11)
    pdf.cell(60, 8, "Communication Clarity:")
    pdf.set_font("helvetica", "", 11)
    pdf.cell(0, 8, str(report.get('communication_clarity', 'N/A')), new_x="LMARGIN", new_y="NEXT")
    
    pdf.set_font("helvetica", "B", 11)
    pdf.cell(60, 8, "Depth of Knowledge:")
    pdf.set_font("helvetica", "", 11)
    pdf.cell(0, 8, str(report.get('depth_of_knowledge', 'N/A')), new_x="LMARGIN", new_y="NEXT")
    pdf.ln(8)

    # Executive Summary
    pdf.set_font("helvetica", "B", 14)
    pdf.set_text_color(124, 58, 237)
    pdf.cell(0, 10, "Executive Summary", border="B", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(3)
    pdf.set_font("helvetica", "I", 11)
    pdf.set_text_color(50, 50, 50)
    pdf.multi_cell(0, 6, str(report.get('summary', 'No summary available.')), new_x="LMARGIN", new_y="NEXT")
    pdf.ln(8)

    # Strengths
    pdf.set_font("helvetica", "B", 14)
    pdf.set_text_color(124, 58, 237)
    pdf.cell(0, 10, "Key Strengths", border="B", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(3)
    pdf.set_font("helvetica", "", 11)
    pdf.set_text_color(0, 0, 0)
    for s in report.get("strengths", []):
        pdf.cell(5, 6, "-", new_x="RIGHT")
        pdf.multi_cell(0, 6, str(s), new_x="LMARGIN", new_y="NEXT")
    pdf.ln(5)

    # Weaknesses
    pdf.set_font("helvetica", "B", 14)
    pdf.set_text_color(124, 58, 237)
    pdf.cell(0, 10, "Areas for Improvement", border="B", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(3)
    pdf.set_font("helvetica", "", 11)
    pdf.set_text_color(0, 0, 0)
    for w in report.get("weaknesses", []):
        pdf.cell(5, 6, "-", new_x="RIGHT")
        pdf.multi_cell(0, 6, str(w), new_x="LMARGIN", new_y="NEXT")
    pdf.ln(5)

    # Transcript
    pdf.add_page()
    pdf.set_font("helvetica", "B", 14)
    pdf.set_text_color(124, 58, 237)
    pdf.cell(0, 10, "Interview Transcript", border="B", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(5)
    
    for m in transcript:
        role = str(m.get("role", "?")).upper()
        content = str(m.get("content", ""))
        
        pdf.set_font("helvetica", "B", 10)
        if role == "ASSISTANT":
            pdf.set_text_color(124, 58, 237)
            role_text = "[AI INTERVIEWER]"
        else:
            pdf.set_text_color(30, 30, 30)
            role_text = "[CANDIDATE]"
            
        pdf.cell(0, 6, role_text, new_x="LMARGIN", new_y="NEXT")
        
        pdf.set_font("helvetica", "", 10)
        pdf.set_text_color(50, 50, 50)
        
        # simple sanitization of unicode chars that might crash fpdf basic fonts
        content = content.encode('latin-1', 'replace').decode('latin-1')
        
        pdf.multi_cell(0, 5, content, new_x="LMARGIN", new_y="NEXT")
        pdf.ln(4)

    return bytes(pdf.output())


def generate_certificate(
    candidate_name: str,
    job_role: str,
    overall_score: float,
    date_completed: str,
) -> bytes:
    """
    Generates a completion certificate PDF.
    """
    from datetime import datetime

    class CertificatePDF(FPDF):
        def header(self):
            # Decorative border
            self.set_draw_color(124, 58, 237)
            self.set_line_width(2)
            self.rect(10, 10, 190, 277)
            self.set_line_width(0.5)
            self.rect(15, 15, 180, 267)

            # Logo area
            self.set_font("helvetica", "B", 36)
            self.set_text_color(124, 58, 237)
            self.cell(0, 40, "VEDRIX", align="C", new_x="LMARGIN", new_y="NEXT")
            self.set_font("helvetica", "", 14)
            self.set_text_color(100, 100, 100)
            self.cell(0, 10, "AI Interview Platform", align="C", new_x="LMARGIN", new_y="NEXT")
            self.ln(20)

    pdf = CertificatePDF()
    pdf.add_page()

    # Certificate Title
    pdf.set_font("helvetica", "B", 32)
    pdf.set_text_color(50, 50, 50)
    pdf.cell(0, 20, "Certificate of Completion", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(10)

    # Subtitle
    pdf.set_font("helvetica", "", 14)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 10, "This is to certify that", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(15)

    # Candidate Name
    pdf.set_font("helvetica", "B", 28)
    pdf.set_text_color(124, 58, 237)
    pdf.cell(0, 15, candidate_name, align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(15)

    # Achievement text
    pdf.set_font("helvetica", "", 14)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 10, "has successfully completed the AI-powered interview", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(10)

    # Job Role
    pdf.set_font("helvetica", "B", 18)
    pdf.set_text_color(50, 50, 50)
    pdf.cell(0, 12, f"for the role of {job_role or 'General Candidate'}", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(15)

    # Score
    pdf.set_font("helvetica", "", 14)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 10, "with an overall performance score of", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(8)

    pdf.set_font("helvetica", "B", 48)
    if overall_score >= 80:
        pdf.set_text_color(34, 197, 94)  # Green
    elif overall_score >= 60:
        pdf.set_text_color(251, 191, 36)  # Amber
    else:
        pdf.set_text_color(239, 68, 68)  # Red

    pdf.cell(0, 25, f"{overall_score:.1f}%", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(20)

    # Date
    pdf.set_font("helvetica", "", 12)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 8, f"Date of Completion: {date_completed}", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(25)

    # Signatures
    pdf.set_font("helvetica", "", 12)
    pdf.set_text_color(50, 50, 50)

    pdf.cell(85, 10, "_______________________", align="L")
    pdf.cell(0, 10, "_______________________", align="R", new_x="LMARGIN", new_y="NEXT")

    pdf.set_font("helvetica", "B", 10)
    pdf.cell(85, 8, "Vedrix AI Platform", align="L")
    pdf.cell(0, 8, "Candidate", align="R", new_x="LMARGIN", new_y="NEXT")

    return bytes(pdf.output())


def generate_certificate_png(
    candidate_name: str,
    job_role: str,
    overall_score: float,
    date_completed: str,
    verification_token: str = "",
) -> bytes:
    """
    Generates a high-resolution PNG certificate image suitable for social sharing.
    Uses Pillow to render directly. Resolution: 1200x800.
    """
    try:
        from PIL import Image, ImageDraw, ImageFont
        import io
    except ImportError:
        # Fallback: return empty PNG if Pillow not available
        import io
        img = Image.new('RGB', (1200, 800), color=(2, 6, 23))
        buffer = io.BytesIO()
        img.save(buffer, format='PNG')
        return buffer.getvalue()

    # Certificate dimensions (LinkedIn optimal share image)
    width, height = 1200, 800

    # Create image with dark background
    img = Image.new('RGB', (width, height), color=(2, 6, 23))  # #020617
    draw = ImageDraw.Draw(img)

    try:
        font_title = ImageFont.truetype("arial.ttf", 48)
        font_subtitle = ImageFont.truetype("arial.ttf", 24)
        font_name = ImageFont.truetype("arial.ttf", 56)
        font_score = ImageFont.truetype("arial.ttf", 72)
        font_body = ImageFont.truetype("arial.ttf", 20)
        font_small = ImageFont.truetype("arial.ttf", 16)
        font_bold = ImageFont.truetype("arialbd.ttf", 20)
    except (IOError, OSError):
        font_title = ImageFont.load_default()
        font_subtitle = ImageFont.load_default()
        font_name = ImageFont.load_default()
        font_score = ImageFont.load_default()
        font_body = ImageFont.load_default()
        font_small = ImageFont.load_default()
        font_bold = ImageFont.load_default()

    # Decorative border
    draw.rectangle([20, 20, width - 20, height - 20], outline=(124, 58, 237), width=4)
    draw.rectangle([30, 30, width - 30, height - 30], outline=(124, 58, 237), width=2)

    # Top accent line
    draw.rectangle([100, 50, width - 100, 54], fill=(124, 58, 237))

    # VEDRIX logo text
    draw.text((width // 2 - 120, 70), "VEDRIX", fill=(124, 58, 237), font=font_title)
    draw.text((width // 2 - 100, 125), "AI Interview Platform", fill=(100, 100, 100), font=font_subtitle)

    # Certificate title
    draw.text((width // 2 - 180, 200), "Certificate of Completion", fill=(255, 255, 255), font=font_title)

    # "This is to certify that"
    draw.text((width // 2 - 120, 280), "This is to certify that", fill=(148, 163, 184), font=font_body)

    # Candidate name
    name_bbox = draw.textbbox((0, 0), candidate_name, font=font_name)
    name_width = name_bbox[2] - name_bbox[0]
    draw.text((width // 2 - name_width // 2, 320), candidate_name, fill=(167, 139, 250), font=font_name)

    # Achievement text
    draw.text((width // 2 - 180, 410), "has successfully completed the AI-powered interview", fill=(148, 163, 184), font=font_body)

    # Job role
    role_text = f"for the role of {job_role or 'General Candidate'}"
    role_bbox = draw.textbbox((0, 0), role_text, font=font_bold)
    role_width = role_bbox[2] - role_bbox[0]
    draw.text((width // 2 - role_width // 2, 445), role_text, fill=(255, 255, 255), font=font_bold)

    # Score label
    draw.text((width // 2 - 120, 510), "with an overall performance score of", fill=(148, 163, 184), font=font_body)

    # Score value with color based on performance
    if overall_score >= 80:
        score_color = (34, 197, 94)  # Green
    elif overall_score >= 60:
        score_color = (251, 191, 36)  # Amber
    else:
        score_color = (239, 68, 68)  # Red

    score_text = f"{overall_score:.1f}%"
    score_bbox = draw.textbbox((0, 0), score_text, font=font_score)
    score_width = score_bbox[2] - score_bbox[0]
    draw.text((width // 2 - score_width // 2, 545), score_text, fill=score_color, font=font_score)

    # Date
    draw.text((width // 2 - 100, 650), f"Date: {date_completed}", fill=(100, 100, 100), font=font_small)

    # Verification token (if provided)
    if verification_token:
        verify_text = f"Verify at: vedrix.ai/verify/{verification_token}"
        verify_bbox = draw.textbbox((0, 0), verify_text, font=font_small)
        verify_width = verify_bbox[2] - verify_bbox[0]
        draw.text((width // 2 - verify_width // 2, 680), verify_text, fill=(124, 58, 237), font=font_small)

    # Bottom accent line
    draw.rectangle([100, height - 60, width - 100, height - 56], fill=(124, 58, 237))

    # Save as PNG
    buffer = io.BytesIO()
    img.save(buffer, format='PNG', quality=95)
    return buffer.getvalue()
