from typing import Dict, Any, List
from fpdf import FPDF

def generate_interview_pdf(
    candidate_name: str,
    job_role: str,
    report: Dict[str, Any],
    transcript: List[Dict[str, str]],
) -> bytes:
    """
    Generates a high-fidelity PDF interview report.
    """
    class PDF(FPDF):
        def header(self):
            self.set_font("helvetica", "B", 15)
            self.set_text_color(124, 58, 237) # Vedrix Purple
            self.cell(0, 10, "Vedrix AI - Candidate Evaluation Report", border=False, align="C", new_x="LMARGIN", new_y="NEXT")
            self.set_draw_color(124, 58, 237)
            self.line(10, 20, 200, 20)
            self.ln(10)

        def footer(self):
            self.set_y(-15)
            self.set_font("helvetica", "I", 8)
            self.set_text_color(128, 128, 128)
            self.cell(0, 10, f"Page {self.page_no()}/{{nb}} - Generated by Vedrix AI Platform", align="C")

    pdf = PDF()
    pdf.add_page()
    
    # Hero Info
    pdf.set_font("helvetica", "B", 12)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(40, 8, "Candidate:")
    pdf.set_font("helvetica", "", 12)
    pdf.cell(0, 8, candidate_name, new_x="LMARGIN", new_y="NEXT")

    pdf.set_font("helvetica", "B", 12)
    pdf.cell(40, 8, "Role:")
    pdf.set_font("helvetica", "", 12)
    pdf.cell(0, 8, job_role, new_x="LMARGIN", new_y="NEXT")

    pdf.set_font("helvetica", "B", 12)
    pdf.cell(40, 8, "Score:")
    pdf.set_font("helvetica", "B", 14)
    pdf.set_text_color(52, 211, 153) # Greenish
    pdf.cell(0, 8, f"{report.get('overall_score', 'N/A')} / 10.0", new_x="LMARGIN", new_y="NEXT")
    
    pdf.set_font("helvetica", "B", 12)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(40, 8, "Decision:")
    pdf.set_font("helvetica", "B", 12)
    pdf.cell(0, 8, str(report.get('hire_recommendation', 'N/A')).upper(), new_x="LMARGIN", new_y="NEXT")
    pdf.ln(10)

    # Score Breakdown
    pdf.set_font("helvetica", "B", 14)
    pdf.set_text_color(124, 58, 237)
    pdf.cell(0, 10, "Score Breakdown", border="B", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(3)
    pdf.set_font("helvetica", "B", 11)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(60, 8, "Technical Accuracy:")
    pdf.set_font("helvetica", "", 11)
    pdf.cell(0, 8, str(report.get('technical_accuracy', 'N/A')), new_x="LMARGIN", new_y="NEXT")
    
    pdf.set_font("helvetica", "B", 11)
    pdf.cell(60, 8, "Communication Clarity:")
    pdf.set_font("helvetica", "", 11)
    pdf.cell(0, 8, str(report.get('communication_clarity', 'N/A')), new_x="LMARGIN", new_y="NEXT")
    
    pdf.set_font("helvetica", "B", 11)
    pdf.cell(60, 8, "Depth of Knowledge:")
    pdf.set_font("helvetica", "", 11)
    pdf.cell(0, 8, str(report.get('depth_of_knowledge', 'N/A')), new_x="LMARGIN", new_y="NEXT")
    pdf.ln(8)

    # Executive Summary
    pdf.set_font("helvetica", "B", 14)
    pdf.set_text_color(124, 58, 237)
    pdf.cell(0, 10, "Executive Summary", border="B", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(3)
    pdf.set_font("helvetica", "I", 11)
    pdf.set_text_color(50, 50, 50)
    pdf.multi_cell(0, 6, str(report.get('summary', 'No summary available.')), new_x="LMARGIN", new_y="NEXT")
    pdf.ln(8)

    # Strengths
    pdf.set_font("helvetica", "B", 14)
    pdf.set_text_color(124, 58, 237)
    pdf.cell(0, 10, "Key Strengths", border="B", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(3)
    pdf.set_font("helvetica", "", 11)
    pdf.set_text_color(0, 0, 0)
    for s in report.get("strengths", []):
        pdf.cell(5, 6, "-", new_x="RIGHT")
        pdf.multi_cell(0, 6, str(s), new_x="LMARGIN", new_y="NEXT")
    pdf.ln(5)

    # Weaknesses
    pdf.set_font("helvetica", "B", 14)
    pdf.set_text_color(124, 58, 237)
    pdf.cell(0, 10, "Areas for Improvement", border="B", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(3)
    pdf.set_font("helvetica", "", 11)
    pdf.set_text_color(0, 0, 0)
    for w in report.get("weaknesses", []):
        pdf.cell(5, 6, "-", new_x="RIGHT")
        pdf.multi_cell(0, 6, str(w), new_x="LMARGIN", new_y="NEXT")
    pdf.ln(5)

    # Transcript
    pdf.add_page()
    pdf.set_font("helvetica", "B", 14)
    pdf.set_text_color(124, 58, 237)
    pdf.cell(0, 10, "Interview Transcript", border="B", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(5)
    
    for m in transcript:
        role = str(m.get("role", "?")).upper()
        content = str(m.get("content", ""))
        
        pdf.set_font("helvetica", "B", 10)
        if role == "ASSISTANT":
            pdf.set_text_color(124, 58, 237)
            role_text = "[AI INTERVIEWER]"
        else:
            pdf.set_text_color(30, 30, 30)
            role_text = "[CANDIDATE]"
            
        pdf.cell(0, 6, role_text, new_x="LMARGIN", new_y="NEXT")
        
        pdf.set_font("helvetica", "", 10)
        pdf.set_text_color(50, 50, 50)
        
        # simple sanitization of unicode chars that might crash fpdf basic fonts
        content = content.encode('latin-1', 'replace').decode('latin-1')
        
        pdf.multi_cell(0, 5, content, new_x="LMARGIN", new_y="NEXT")
        pdf.ln(4)

    return bytes(pdf.output())
