"""Initial Schema

Revision ID: 5bf8ec63040f
Revises: 
Create Date: 2026-05-03 18:56:49.960148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bf8ec63040f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Ensure the initial table exists before altering JSON columns.
    # CI was failing because `interview_session` was not created (UndefinedTableError).
    op.create_table(
        'interview_session',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('candidate_id', sa.Integer(), nullable=False),
        sa.Column('job_drive_id', sa.Integer(), nullable=True),
        sa.Column('session_type', sa.String(), nullable=False),
        sa.Column('status', sa.String(), nullable=True),
        sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
        sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
        sa.Column('duration', sa.Integer(), nullable=True),
        sa.Column('overall_score', sa.Float(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('questions', sa.JSON(), nullable=True),
        sa.Column('responses', sa.JSON(), nullable=True),
        sa.Column('ai_feedback', sa.JSON(), nullable=True),
        sa.Column('skill_matrix', sa.JSON(), nullable=True),
        sa.Column('confidence_scores', sa.JSON(), nullable=True),
        sa.Column('evidence_log', sa.JSON(), nullable=True),
        sa.Column('agent_states', sa.JSON(), nullable=True),
        sa.Column('bias_metrics', sa.JSON(), nullable=True),
        sa.Column('question_difficulty', sa.JSON(), nullable=True),
        sa.Column('advisor_ready_to_close', sa.Boolean(), nullable=False),
        sa.Column('advisor_confidence', sa.Float(), nullable=True),
        sa.Column('advisor_reason', sa.Text(), nullable=True),
        sa.Column('advisor_reason_category', sa.String(), nullable=True),
        sa.Column('advisor_suggested_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('advisor_action_taken', sa.Boolean(), nullable=False),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('interview_plan_id', sa.Integer(), nullable=True),
        sa.Column('workflow_state', sa.String(), nullable=True),
        sa.Column('empathy_timeline', sa.JSON(), nullable=True),
        sa.Column('qa_quality_score', sa.Float(), nullable=True),
        sa.Column('proctor_consent_granted', sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['candidate_id'], ['user.id']),
        sa.ForeignKeyConstraint(['job_drive_id'], ['job_drive.id']),
        sa.ForeignKeyConstraint(
            ['interview_plan_id'],
            ['interview_plan.id'],
            name='fk_interview_session_plan_id',
        ),
    )
    # ### commands auto generated by Alembic - please adjust! ###
    # These alters are now safe because the table exists.
    op.alter_column('interview_session', 'questions',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('interview_session', 'responses',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('interview_session', 'ai_feedback',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('interview_session', 'ai_feedback',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('interview_session', 'responses',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('interview_session', 'questions',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###

    op.drop_table('interview_session')
